[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  SITE_URL = "https://trendvideo.online"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/telegram-webhook"
  to = "/.netlify/functions/telegram-webhook"
  status = 200
  force = true

[[redirects]]
  from = "/api/setup-webhook"
  to = "/.netlify/functions/setup-webhook"
  status = 200
  force = true
