[build]
  command = "npm run build"
  publish = "dist"
  functions = "dist/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"